/**
 * bestiary-catalog.ts
 *
 * Pure markdown rendering for the screenshot bestiary, plus the pure mapping
 * from fixture-matrix scenes to catalog entries. Keeping this separate from the
 * Playwright orchestration so it's testable without spinning up Chromium.
 */

import type { SceneAxis, SceneCloseup } from "../src/test/scenes";

export type CaptureMeta = {
  /** Slug used in the filename, e.g. "list-overview". */
  slug: string;
  /** Short description rendered as a caption under the image. */
  description?: string;
  /** Relative path or filename of the PNG, used in the markdown link. */
  filename: string;
};

export type ScenarioMeta = {
  /** Family the scenario belongs to (groups headings in the catalog). */
  family: string;
  /** Scenario slug. */
  slug: string;
  /** Title shown in the catalog. */
  title: string;
  /** Markdown paragraph(s) explaining what the scenario shows. */
  description: string;
  /** Ordered list of captures for this scenario. */
  captures: CaptureMeta[];
};

export type CatalogOptions = {
  /** ISO date string (YYYY-MM-DD) for the front matter. */
  date: string;
  /** Optional intro paragraph above the first family. */
  intro?: string;
};

/**
 * Render a markdown catalog from a list of scenarios. Groups consecutive
 * scenarios with the same `family` under a single `##` heading. Each scenario
 * becomes a `###` subsection with its description and embedded screenshots
 * (Obsidian `![[…]]` wikilink syntax for in-vault rendering).
 */
export function renderCatalog(
  scenarios: ScenarioMeta[],
  options: CatalogOptions,
): string {
  const lines: string[] = [];

  lines.push("---");
  lines.push("ticket: PRO-219");
  lines.push(`date: ${options.date}`);
  lines.push("tags: ui, screenshots, bestiary");
  lines.push("---");
  lines.push("");
  lines.push("# UI screenshot bestiary");
  lines.push("");
  lines.push(
    "Generated by `just screenshots-bestiary` (or `pnpm run screenshots:bestiary`).",
  );
  lines.push(
    "Every entry is a fixture-matrix scene injected via `window.__test_scenes`;",
  );
  lines.push(
    "no Rust backend is involved. See PRO-219 (origin) and PRO-410 (matrix",
  );
  lines.push("convergence) for context.");
  lines.push("");

  if (options.intro) {
    lines.push(options.intro);
    lines.push("");
  }

  let currentFamily: string | null = null;
  for (const scenario of scenarios) {
    if (scenario.family !== currentFamily) {
      lines.push(`## ${scenario.family}`);
      lines.push("");
      currentFamily = scenario.family;
    }

    lines.push(`### ${scenario.title}`);
    lines.push("");
    lines.push(scenario.description.trim());
    lines.push("");

    for (const capture of scenario.captures) {
      lines.push(`![[${capture.filename}]]`);
      if (capture.description) {
        lines.push("");
        lines.push(`_${capture.description.trim()}_`);
      }
      lines.push("");
    }
  }

  return lines.join("\n");
}

/**
 * Build the canonical filename for a scenario capture:
 * `{scenario-slug}-{capture-slug}.png`. Slugs are kebab-case and unique
 * within their level — this keeps file listings sortable by family.
 */
export function captureFilename(
  scenarioSlug: string,
  captureSlug: string,
): string {
  return `${scenarioSlug}-${captureSlug}.png`;
}

// ─── Fixture-matrix → catalog mapping ──────────────────────────────────────────
//
// The bestiary's primary content is the fixture matrix (`src/test/scenes.ts`):
// every matrix cell becomes a catalog entry, so a scene added to the matrix
// shows up in the bestiary with no extra wiring. Each scene yields one
// full-viewport capture plus any bestiary-only clipped close-ups it declares
// (`Scene.bestiaryCloseups`), grouped in the catalog by its declarative `axis`.

/** The fields of a fixture-matrix `Scene` the catalog mapping reads. */
export type MatrixSceneInput = {
  id: string;
  title: string;
  axis: SceneAxis;
  description: string;
  /** Bestiary-only clipped close-ups; see `SceneCloseup` in scenes.ts. */
  bestiaryCloseups?: readonly SceneCloseup[];
  /** Documented in the bestiary but not part of the matrix; see scenes.ts. */
  bestiaryOnly?: boolean;
};

/** Catalog family for scenes documented in the bestiary but not in the matrix. */
const BESTIARY_ONLY_FAMILY = "Bestiary-only (not in the fixture matrix)";

/** Catalog family heading per matrix axis. */
const AXIS_FAMILY: Record<SceneAxis, string> = {
  state: "Matrix — state axis",
  data: "Matrix — data axis",
  view: "Matrix — view axis",
};

/** Axis grouping order in the catalog. */
const AXIS_ORDER: SceneAxis[] = ["state", "data", "view"];

/**
 * Map a fixture-matrix scene to a catalog scenario entry: the full-viewport
 * capture (`{id}-view.png`, no caption — the scene description explains it),
 * followed by one entry per declared `bestiaryCloseup` (`{id}-{slug}.png`).
 * Filed under its axis family.
 */
export function matrixSceneToMeta(scene: MatrixSceneInput): ScenarioMeta {
  const closeups = scene.bestiaryCloseups ?? [];
  return {
    family: scene.bestiaryOnly ? BESTIARY_ONLY_FAMILY : AXIS_FAMILY[scene.axis],
    slug: scene.id,
    title: scene.title,
    description: scene.description,
    captures: [
      { slug: "view", filename: captureFilename(scene.id, "view") },
      ...closeups.map((c) => ({
        slug: c.slug,
        description: c.description,
        filename: captureFilename(scene.id, c.slug),
      })),
    ],
  };
}

/**
 * Order scenes so same-axis cells are contiguous (state → data → view), which
 * makes the catalog render one `##` heading per axis. Lossless: any scene whose
 * axis isn't in `AXIS_ORDER` is preserved at the end rather than dropped, so a
 * future axis can't silently fall out of the bestiary.
 */
export function orderScenesByAxis<T extends { axis: SceneAxis }>(
  scenes: T[],
): T[] {
  const known = new Set<SceneAxis>(AXIS_ORDER);
  return [
    ...AXIS_ORDER.flatMap((axis) => scenes.filter((s) => s.axis === axis)),
    ...scenes.filter((s) => !known.has(s.axis)),
  ];
}

/**
 * Bestiary render order: matrix scenes first, grouped by axis, then any
 * bestiary-only scenes as a trailing section — so the catalog reads as the
 * matrix followed by its explicitly-marked extras.
 */
export function orderBestiaryScenes<
  T extends { axis: SceneAxis; bestiaryOnly?: boolean },
>(scenes: T[]): T[] {
  return [
    ...orderScenesByAxis(scenes.filter((s) => !s.bestiaryOnly)),
    ...scenes.filter((s) => s.bestiaryOnly),
  ];
}
