/**
 * bestiary-catalog.ts
 *
 * Pure markdown rendering for the screenshot bestiary. Keeping this separate
 * from the Playwright orchestration so it's testable without spinning up
 * Chromium.
 */

export type CaptureMeta = {
  /** Slug used in the filename, e.g. "list-overview". */
  slug: string;
  /** Short description rendered as a caption under the image. */
  description?: string;
  /** Relative path or filename of the PNG, used in the markdown link. */
  filename: string;
};

export type ScenarioMeta = {
  /** Family the scenario belongs to (groups headings in the catalog). */
  family: string;
  /** Scenario slug. */
  slug: string;
  /** Title shown in the catalog. */
  title: string;
  /** Markdown paragraph(s) explaining what the scenario shows. */
  description: string;
  /** Ordered list of captures for this scenario. */
  captures: CaptureMeta[];
};

export type CatalogOptions = {
  /** ISO date string (YYYY-MM-DD) for the front matter. */
  date: string;
  /** Optional intro paragraph above the first family. */
  intro?: string;
};

/**
 * Render a markdown catalog from a list of scenarios. Groups consecutive
 * scenarios with the same `family` under a single `##` heading. Each scenario
 * becomes a `###` subsection with its description and embedded screenshots
 * (Obsidian `![[…]]` wikilink syntax for in-vault rendering).
 */
export function renderCatalog(
  scenarios: ScenarioMeta[],
  options: CatalogOptions,
): string {
  const lines: string[] = [];

  lines.push("---");
  lines.push("ticket: PRO-219");
  lines.push(`date: ${options.date}`);
  lines.push("tags: ui, screenshots, bestiary");
  lines.push("---");
  lines.push("");
  lines.push("# UI screenshot bestiary");
  lines.push("");
  lines.push(
    "Generated by `just screenshots-bestiary` (or `pnpm run screenshots:bestiary`).",
  );
  lines.push(
    "Each scenario is set up via store injection (`window.__test_store`); no Rust",
  );
  lines.push("backend is involved. See PRO-219 for context.");
  lines.push("");

  if (options.intro) {
    lines.push(options.intro);
    lines.push("");
  }

  let currentFamily: string | null = null;
  for (const scenario of scenarios) {
    if (scenario.family !== currentFamily) {
      lines.push(`## ${scenario.family}`);
      lines.push("");
      currentFamily = scenario.family;
    }

    lines.push(`### ${scenario.title}`);
    lines.push("");
    lines.push(scenario.description.trim());
    lines.push("");

    for (const capture of scenario.captures) {
      lines.push(`![[${capture.filename}]]`);
      if (capture.description) {
        lines.push("");
        lines.push(`_${capture.description.trim()}_`);
      }
      lines.push("");
    }
  }

  return lines.join("\n");
}

/**
 * Build the canonical filename for a scenario capture:
 * `{scenario-slug}-{capture-slug}.png`. Slugs are kebab-case and unique
 * within their level — this keeps file listings sortable by family.
 */
export function captureFilename(
  scenarioSlug: string,
  captureSlug: string,
): string {
  return `${scenarioSlug}-${captureSlug}.png`;
}
