FROM alpine:3.21
ARG TARGETARCH
RUN apk add --no-cache curl jq \
 && addgroup -S -g 65532 protospy \
 && adduser -S -u 65532 -G protospy protospy
COPY publish/linux/${TARGETARCH}/protospy /usr/local/bin/protospy
USER protospy
EXPOSE 3100
ENTRYPOINT ["/usr/local/bin/protospy"]
