# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: echo.proto
# Protobuf Python Version: 6.31.1
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    6,
    31,
    1,
    '',
    'echo.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\necho.proto\x12\x0b\x63onformance\"/\n\x0b\x45\x63hoRequest\x12\x0f\n\x07message\x18\x01 \x01(\t\x12\x0f\n\x07payload\x18\x02 \x01(\x0c\"B\n\x0c\x45\x63hoResponse\x12\x0f\n\x07message\x18\x01 \x01(\t\x12\x0f\n\x07payload\x18\x02 \x01(\x0c\x12\x10\n\x08sequence\x18\x03 \x01(\x05\"/\n\rStreamRequest\x12\x0f\n\x07message\x18\x01 \x01(\t\x12\r\n\x05\x63ount\x18\x02 \x01(\x05\x32\xd8\x01\n\x04\x45\x63ho\x12@\n\tUnaryEcho\x12\x18.conformance.EchoRequest\x1a\x19.conformance.EchoResponse\x12G\n\x0cServerStream\x12\x1a.conformance.StreamRequest\x1a\x19.conformance.EchoResponse0\x01\x12\x45\n\nBidiStream\x12\x18.conformance.EchoRequest\x1a\x19.conformance.EchoResponse(\x01\x30\x01\x62\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'echo_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  DESCRIPTOR._loaded_options = None
  _globals['_ECHOREQUEST']._serialized_start=27
  _globals['_ECHOREQUEST']._serialized_end=74
  _globals['_ECHORESPONSE']._serialized_start=76
  _globals['_ECHORESPONSE']._serialized_end=142
  _globals['_STREAMREQUEST']._serialized_start=144
  _globals['_STREAMREQUEST']._serialized_end=191
  _globals['_ECHO']._serialized_start=194
  _globals['_ECHO']._serialized_end=410
# @@protoc_insertion_point(module_scope)
