// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { BodyChunk } from "./BodyChunk";

export type BodyContent = { offset: number, length: number, payload: BodyChunk, };
