// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { BodyContent } from "./BodyContent";
import type { Headers } from "./Headers";

export type BodyData = { content: BodyContent | null, trailers: Headers | null, at_end: boolean, total_bytes: number, };
