// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { BodyData } from "./BodyData";
import type { Direction } from "./Direction";
import type { Headers } from "./Headers";
import type { InitialBody } from "./InitialBody";

export type Event = { "request": { method: string, uri: string, version: string, headers: Headers, body: InitialBody, trailers: Headers | null, } } | { "response": { status: string, version: string, headers: Headers, elapsed_ms: number, body: InitialBody, trailers: Headers | null, } } | { "bodydata": BodyData } | { "error": { direction: Direction, message: string, } };
