// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { BodyData } from "./BodyData";
import type { Direction } from "./Direction";
import type { InitialBody } from "./InitialBody";
import type { ProxyHeaders } from "./ProxyHeaders";

export type Event = { "type": "request", method: string, uri: string, version: string, headers: ProxyHeaders, body: InitialBody, } | { "type": "response", status: string, version: string, headers: ProxyHeaders, elapsed_ms: number, body: InitialBody, } | { "type": "bodydata" } & BodyData | { "type": "error", direction: Direction, message: string, };
