// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { Direction } from "./Direction";
import type { Event } from "./Event";
import type { ExchangeMeta } from "./ExchangeMeta";

export type EventMessage = { exchange: ExchangeMeta, direction: Direction, event: Event, };
