// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { Protocol } from "./Protocol";

export type Service = { name: string, addr: string, target: string, protocol: Protocol | null, subscribers: number, };
