name: protospy-ci

on:
  push:
    branches: [main]
    paths:
      - "Cargo.lock"
      - "Cargo.toml"
      - ".cargo"
      - "src/**"
      - ".github/workflows/protospy-ci.yml"
  pull_request:
    paths:
      - "Cargo.lock"
      - "Cargo.toml"
      - ".cargo"
      - "src/**"
      - ".github/workflows/protospy-ci.yml"

jobs:
  test:
    runs-on: ubuntu-latest
    timeout-minutes: 15
    env:
      CC_x86_64_unknown_linux_musl: musl-gcc
    steps:
      - uses: actions/checkout@v6
      - uses: dtolnay/rust-toolchain@stable
        with:
          targets: x86_64-unknown-linux-musl
      - run: sudo apt-get update && sudo apt-get install -y musl-tools
      - uses: Swatinem/rust-cache@v2
        with:
          shared-key: x86_64-musl
      # just build, to separate compiler output
      - run: cargo test --all-features --no-run --target x86_64-unknown-linux-musl
      - run: cargo fmt --check
      - run: cargo clippy --all-targets --all-features --no-deps --target x86_64-unknown-linux-musl -- -D warnings
      - run: cargo test --all-features --target x86_64-unknown-linux-musl
      - name: Check for outdated bindings
        run: git diff --exit-code bindings && [[ $(git ls-files --others --exclude-standard bindings | wc -l) -eq 0 ]]
